name: Linter
on:
 push:
   branches:
     - '**'
jobs:
 lint:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'
     - name: Go to api
       run: cd api
     - name: Install dependencies api
       run: pip install -r requirements.txt
     - name: Go back
       run: cd ../
     - name: Go to scrapper
       run: cd scrapper
     - name: Install dependencies scrapper
       run: pip install -r requirements.txt
     - name: Install Ruff
       run: pip install ruff
     - name: Run Ruff
       run: ruff lint
