name: Unittests
on:
  push:
    branches:
      - '**'
jobs:
 unittesting:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.10
     - name: Go to scrapper dir
       run: cd scrapper
     - name: Install dependencies
       run: pip install -r requirements.txt
     - name: Go to tests dir
       run: cd workers/tests
     - name: Run Unit Tests
       run: python -m unittest discover .